### ISSUE TITLE
gcc-c++ issue

### ISSUE THREAD

**Issue by S4mk0** [Constantin-Hentgen/Dotfiles#2]
![image_2024-09-15_222520679](https://github.com/user-attachments/assets/bdca3e3b-52db-49cf-958e-26eacb7c6190)

**Comment by S4mk0** [comment]
ajouter le packet manquant dans la liste de paquets à installer dans le code ansible ?

**Comment by S4mk0** [comment]
try: install package "gcc" 
result -> problem still the same

**Comment by Constantin-Hentgen** [comment]
@S4mk0  
- Le nom de package `gcc-c++` est le nom du package [dnf](https://docs.fedoraproject.org/en-US/quick-docs/dnf/), il ne fonctionne pas pour apt :(

- Son alternative serait `sudo apt install build-essential`

- Pour simplifier les choses, j’ai retiré une bonne partie des packages, j’ai laissé que les packages des utilitaires directement, j’oublie les dépendances pour favoriser la portabilité (support des distros debian-based, freebsd et fedora)

=> pour ne pas avoir d’erreurs, fait un `git pull` sur la branche `master` puis relance `ansible-playbook ansible/playbook.yml --ask-become-pass -e "username=sam"`
