### ISSUE TITLE
main issue

### ISSUE THREAD

**Issue by S4mk0** [Constantin-Hentgen/Dotfiles#3]
![image_2024-09-15_230903759](https://github.com/user-attachments/assets/981b098d-84e7-4627-8048-eb2462ad3dd1)

**Comment by Constantin-Hentgen** [comment]
Est-ce que tu peux envoyer l’ID et le `commit message` du commit le plus récent que tu vois quand tu fais `git log` ?

**Comment by S4mk0** [comment]
tjrs d'actualité ?
